### ISSUE TITLE
there is aliasing problem

### ISSUE THREAD

**Issue by mumin16** [zsbzsb/Motion#2]
there is aliasing problem

**Comment by eXpl0it3r** [comment]
So much information, it's astonishing. I'm not even sure where to begin. :smirk:

**Comment by mumin16** [comment]
actually, I got many errors. 

1- SFML_DIR is problem in cmake.
my solution:
i removed line26 and line58(sfml-depends) from src->motion->cmakelist
and i manually added sfml-depends in vs2015.

2-at compile in vs2015-x64.
a)DataSource.cpp(169-179): error C2065: 'PIX_FMT_RGBA': undeclared identifier
my solution:
in DataSource.cpp, i added:
enum    PixelFormat {
    PIX_FMT_NONE = -1, PIX_FMT_YUV420P, PIX_FMT_YUYV422, PIX_FMT_RGB24,
    PIX_FMT_BGR24, PIX_FMT_YUV422P, PIX_FMT_YUV444P, PIX_FMT_YUV410P,
    PIX_FMT_YUV411P, PIX_FMT_GRAY8, PIX_FMT_MONOWHITE, PIX_FMT_MONOBLACK,
    PIX_FMT_PAL8, PIX_FMT_YUVJ420P, PIX_FMT_YUVJ422P, PIX_FMT_YUVJ444P,
    PIX_FMT_XVMC_MPEG2_MC, PIX_FMT_XVMC_MPEG2_IDCT, PIX_FMT_UYVY422, PIX_FMT_UYYVYY411,
    PIX_FMT_BGR8, PIX_FMT_BGR4, PIX_FMT_BGR4_BYTE, PIX_FMT_RGB8,
    PIX_FMT_RGB4, PIX_FMT_RGB4_BYTE, PIX_FMT_NV12, PIX_FMT_NV21,
    PIX_FMT_ARGB, PIX_FMT_RGBA, PIX_FMT_ABGR, PIX_FMT_BGRA,
    PIX_FMT_GRAY16BE, PIX_FMT_GRAY16LE, PIX_FMT_YUV440P, PIX_FMT_YUVJ440P,
    PIX_FMT_YUVA420P, PIX_FMT_VDPAU_H264, PIX_FMT_VDPAU_MPEG1, PIX_FMT_VDPAU_MPEG2,
    PIX_FMT_VDPAU_WMV3, PIX_FMT_VDPAU_VC1, PIX_FMT_RGB48BE, PIX_FMT_RGB48LE,
    PIX_FMT_RGB565BE, PIX_FMT_RGB565LE, PIX_FMT_RGB555BE, PIX_FMT_RGB555LE,
    PIX_FMT_BGR565BE, PIX_FMT_BGR565LE, PIX_FMT_BGR555BE, PIX_FMT_BGR555LE,
    PIX_FMT_VAAPI_MOCO, PIX_FMT_VAAPI_IDCT, PIX_FMT_VAAPI_VLD, PIX_FMT_YUV420P16LE,
    PIX_FMT_YUV420P16BE, PIX_FMT_YUV422P16LE, PIX_FMT_YUV422P16BE, PIX_FMT_YUV444P16LE,
    PIX_FMT_YUV444P16BE, PIX_FMT_VDPAU_MPEG4, PIX_FMT_DXVA2_VLD, PIX_FMT_RGB444BE,
    PIX_FMT_RGB444LE, PIX_FMT_BGR444BE, PIX_FMT_BGR444LE, PIX_FMT_Y400A,
    PIX_FMT_NB
};
b) Conversion problems:
-DataSource.cpp(187) argument 1 from 'AVPixelFormat' to 'PixelFormat'
-DataSource.cpp(198) argument 7 from 'PixelFormat' to 'AVPixelFormat'
-DataSource.cpp(590) argument 1 from 'PixelFormat' to 'AVPixelFormat'
-DataSource.cpp(597) argument 3 from 'PixelFormat' to 'AVPixelFormat'

classical solution:
(AVPixelFormat) x;    // c-like cast notation 
or
(PixelFormat) x;    // c-like cast notation 

3-aliasing problem:
i downloaded any video from youtube. i used it in motion's example. but there is aliasing problem...

**Comment by eXpl0it3r** [comment]
1) You need to set `SFML_ROOT`, see the FindSFML.cmake for more information.
2) No idea, never looked at the source.
3) What do you mean with aliasing problem?

**Comment by zsbzsb** [comment]
1) Do as @eXpl0it3r said.
2) [`libavutil/pixfmt.h`](https://www.ffmpeg.org/doxygen/2.6/pixfmt_8h.html)(what you manually defined) is included from [`libswscale/swscale.h`](https://github.com/FFmpeg/FFmpeg/blob/release/2.8/libswscale/swscale.h#L34) which I already include [here](https://github.com/zsbzsb/Motion/blob/master/Motion/include/Motion/DataSource.hpp#L32). Seeing as you goofed up the SFML part of CMake you may have messed up the FFMPEG options also. Make sure the CMake option `FFMPEG_INCLUDE_DIR` is set to the directory containing all of the FFMPEG headers.
3) I have no clue what you mean. If you mean screen tearing that is unrelated to Motion.
